services:
  rabbitmq:
    container_name: guide-rabbit
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_USER=rabbitmq

